<template>
  <div>
<el-row>
  <el-switch
    v-model="value"
    active-color="#13ce66"
    inactive-color="#ff4949"
  ></el-switch>
</el-row>
    <br>
    <el-row>
      <el-switch
      v-model="value"
      active-text="按月付费"
      inactive-text="按年付费"
      active-color="#13ce66"
      inactive-color="#ff4949"
      ></el-switch>
    </el-row>
    <br>
    <el-row>
      <el-switch
      v-model="num"
      active-value="100"
      inactive-value="0"
      active-color="#13ce66"
      inactive-color="#ff4949"
      active-text="me"
      inactive-text="your"
      >
      </el-switch>
    </el-row>
    <br>
    <el-row>
      <el-switch
        v-model="value"
      active-color="#13ce66"
      inactive-color="#ff4949"
        disabled
      >
      </el-switch>
    </el-row>
    <!--
    active-**
    inactive-**
    -->
  </div>
</template>
<script>
export default {
  name:"uiswitch",
  data(){
    return{
      value:true,
      num:100,
    }
  },
  methods:{

  }
}
</script>
<style scoped>

</style>
